### ISSUE TITLE
dependencies needs upgrade

### ISSUE THREAD

**Issue by Alvin2281** [hi-manshu/Flutter-Apps-Collection#1]
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

Because flutterredux depends on flutter_redux >=0.1.1 <0.4.0 which requires SDK version <2.0.0, version solving failed.
pub get failed (1)

**Comment by hi-manshu** [comment]
Please feel free to fork and update it. I am not currently managing it.
